# Generated by Django 3.0.8 on 2020-07-25 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dram', models.CharField(max_length=250)),
                ('company', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('SM', 'Single Malt Scotch'), ('BS', 'Blended Scotch'), ('BMS', 'Blended Malt Scotch'), ('IB', 'Irish Blend'), ('SPS', 'Single Pot Still Irish'), ('B', 'Bourbon'), ('CW', 'Canadian Whisky'), ('RW', 'Rye Whiskey'), ('JW', 'Japanese Whisky'), ('WW', 'World/Misc Whisk(e)y')], default='WW', max_length=30)),
                ('abv', models.DecimalField(decimal_places=2, max_digits=4)),
                ('nosing', models.TextField(default='Add nosing notes here.')),
                ('tasting', models.TextField(default='Add tasting notes here.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
