# Generated by Django 3.0.8 on 2020-07-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dram',
            name='region',
            field=models.CharField(choices=[('SP', 'Speyside'), ('HL', 'Highlands/Other Islands'), ('IS', 'Islay'), ('LL', 'Lowlands'), ('CT', 'Campbelltown'), ('KT', 'Kentucky'), ('TN', 'Tennessee'), ('OS', 'Other U.S. State'), ('N', 'N/A')], default='N', max_length=30),
        ),
    ]
